version: "3"
services:
  news-challenge-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_NEWS_API_KEY=${REACT_APP_NEWS_API_KEY}
      - REACT_APP_NEWS_API=${REACT_APP_NEWS_API}
    env_file:
      - .env
